services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-vfeticr-viewer
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vfeticr_viewer
      POSTGRES_USER: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_vfeticr_viewer_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_vfeticr_viewer_data: