spring.application.name=vfeticr-viewer

spring.profiles.default=prod

# set in enviroment for development
spring.profiles.active=${SPRING_PROFILES_ACTIVE:}

# Common Datasource settings
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Common JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#this property is default, need to check
#hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
