
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.continue-on-error=false

spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=UTF-8
