spring.application.name=vfeticr-viewer

spring.profiles.default=prod

# set in enviroment for development
spring.profiles.active=${SPRING_PROFILES_ACTIVE:}

# Common Datasource settings
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
## DB credentials with default values for local development, should be set in environment for production
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vfeticr_viewer}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:mysecretpassword}

# Common JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#this property is default, need to check
#hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
